# jekyll settings

title:  "Cascading Style Sheets - Designing for the Web"
author:
  name: "Bert Bos, HÃ¥kon Wium Lie"



########
# more settings

collections:
  chapters:
      output: false

markdown: kramdown



exclude:
- README.md


safe: true
lsi: false
